### ISSUE TITLE
Use Time.at(time) instead of Time.now for fallback

### ISSUE THREAD

**Issue by dannyk81** [ecwws/fluent-plugin-elasticsearch-timestamp-check#8]
I'm curious why not use `Time.at(time)` in the fallback option instead of `Time.now`, here https://github.com/ecwws/fluent-plugin-elasticsearch-timestamp-check/blob/00ca651809d295bf26f6f7b26997c5d24199b89d/lib/fluent/plugin/filter_elasticsearch_timestamp_check.rb#L50

AFAIU, every event that is ingested in fluntd has an internal `time` key, either extracted from the event record (using formatting/parsing) or by using the time when it was ingested, since the event can travel through the pipeline, by the time it reaches this plugin `Time.now` doesn't represent the actual ingestion time of the event.

Any thoughts? @ecwws @cosmo0920

**Comment by cosmo0920** [comment]
Because msgpack cannot handle `Time` object.
In record, users have to insert timestamp as `String` object or something which contains Time information.
For using elasticsearch, milliseconds time resolution(`.%L`) is enough.

**Comment by dannyk81** [comment]
Thanks @cosmo0920, I'm probably missing something, but can't we use this:
```
Time.at(time).strftime('%Y-%m-%dT%H:%M:%S.%L%z')
```

Here's the full snippet (lines 48 - 52):
```
      unless record['fluent_converted_timestamp']
        record['@timestamp'] = record['fluent_added_timestamp'] =
          Time.at(time).strftime('%Y-%m-%dT%H:%M:%S.%L%z')
        $log.debug("Timestamp added: #{record['@timestamp']}")
      end
```

The filter should have access to `tag`, `time` and `record` ?

**Comment by cosmo0920** [comment]
> The filter should have access to tag, time and record ?

Within `#filter`, we should access tag, time, and record but we can only modify record.

**Comment by dannyk81** [comment]
Yes I uderstand, but I'm not proposing to modify the `time` object, just to derive the values for keys `@timestamp` & `fluent_added_timestamp` in the `record` *from* `time`

```
record['@timestamp'] = record['fluent_added_timestamp'] = Time.at(time).strftime('%Y-%m-%dT%H:%M:%S.%L%z')
```

This should work isn't it?

**Comment by ecwws** [comment]
For practical purposes, the difference between event time and the time obtained using Time.now are probably negligible. However, the point you brought up, using `time` field of the object that was supplied to the plugin does have a certain valid use case: parser plugins that has a setting of `time_key` will cause the `time` field to be set using the field from the source data.

Let me test a couple things out, then I'll have it fixed up.

**Comment by dannyk81** [comment]
Thanks @ecwws 😄 

In our deployment, we are using this plugin on the aggregation fluentd nodes, before sending the events to Elasticsearch. We try to keep our fluentd forwarders configuration as basic/simple as possible.

In this kind of setup, since the forwarders have a flush interval of 5 seconds, using `Time.now` on the aggregation nodes will always introduce a delay in the value of @timestamp compared to the actual ingestion time of the even.

**Comment by dannyk81** [comment]
@ecwws any luck with this?

**Comment by dannyk81** [comment]
@ecwws ping 😄

**Comment by ecwws** [comment]
@dannyk81 sorry, work suddenly got really really busy, I'm going to try to figure this out tonight

**Comment by ecwws** [comment]
@dannyk81 sorry it took long, 0.2.8 should be using the event time instead of Time.now for added timestamp
