### ISSUE TITLE
Support nanosecond (epoch nano) timestamp

### ISSUE THREAD

**Issue by dannyk81** [ecwws/fluent-plugin-elasticsearch-timestamp-check#9]
Since fluentd supports nanosecond timestamp, could we extend this plugin to support epoch nano as well?

We have one source that currently set `timestamp` field to epoch nano, so at the moment we need to do a transformation to millisecs, would be nice if the plugin supported it out-of-the-box.

**Comment by cosmo0920** [comment]
Currently, Elsaticsearch does not handle micro and nano-second precision.
But I think that it's worth handling micro or nano or pico or etc. precision timestamp.

**Comment by cosmo0920** [comment]
See: https://github.com/elastic/elasticsearch/issues/10005

**Comment by dannyk81** [comment]
I agree, Elasticsearch only handles millsecs but the plugin doesn't handles the cases where the `timestamp` key in the record is provided in nanoseconds.

We could simply convert the epoch nano to epoch milli and create the `@timestamp` from that, wdyt?

**Comment by dannyk81** [comment]
Actually, it should handle microseconds and nanoseconds (as well as seconds and millisecs)

**Comment by ecwws** [comment]
fixed as of 0.2.6

**Comment by dannyk81** [comment]
@ecwws @cosmo0920 thank you! 😄
